### ISSUE TITLE
Oracle thread started but not stopped, causes classloader leak

### ISSUE THREAD

**Issue by bradcupit** [mjiderhamn/classloader-leak-prevention#23]
After using your excellent library we (unfortunately) had a new Oracle thread start running. This thread did not get shutdown on reload, thus causing a classloader leak.

We have the Oracle JDBC driver in our `<TOMCAT_HOME>/lib` (though we're currently not using the Oracle JDBC driver). I'm not sure if this is relevant.

I must confess I don't understand why the oracle thread's context classloader should be the System classloader. Does that prevent `stopThreads()` from stopping it?

**Work around**
I extended ClassLoaderLeakPreventor and overrode `contextInitialized()`, skipping the code that spins up the Oracle thread.

**Comment by mjiderhamn** [comment]
Having some time to contemplate on this now. What do you think about keeping `initOracleJdbcThread()`, but after loading the class (and thus spawning the thread) finding the `oracle.jdbc.driver.OracleTimeoutPollingThread` and setting its `inheritedAccessControlContext` to `new AccessControlContext(null, false)`?

**Comment by hdeadman** [comment]
That might help. I do worry about the case where an application that doesn't use Oracle but finds the Oracle jar in its classpath (which would be the case for an app running in Weblogic that didn't use Oracle) since a thread is being spawned that otherwise wouldn't be spawned. It might be worth adding a configuration parameter that allowed someone to turn off the Oracle check if they choose.

ClassLoaderLeakPreventor.disableOracleChecks (not sure what the default should be, false may be OK b/c for many users (of Tomcat, Jetty, etc) the existence of the Oracle class in the classpath is probably a reasonable indicator they are using Oracle).

**Comment by mjiderhamn** [comment]
I spent some more time with this and I believe I found a more proper workaround, hopefully also covering more similar cases. At the same time I introduced a setting for the spawning of the Oracle timeout thread in question, `ClassLoaderLeakPreventor.startOracleTimeoutThread` which defaults to `true`.

I don't have the time to test right now, so if anyone would care to help me out - especially with the Oracle cases - that would be appreciated. You'd need to pull the [AccessControlContext branch](https://github.com/mjiderhamn/classloader-leak-prevention/tree/AccessControlContext) and compile from there.
Just reviewing and commenting on [the changes](https://github.com/mjiderhamn/classloader-leak-prevention/commit/716b9fb84152afea33cbb13c926ea38d2b4a5921) would also be appreciated.

**Comment by hdeadman** [comment]
I added the listener from the AccessControlContext branch to one of the applications I work on and deployed it to Weblogic 12 and Jetty 9.0.5 (from Maven). I deployed to Weblogic several times to see if it leaked but it wasn't a good test b/c I hadn't checked this application to see if it leaked recently and there are other applications deployed to the server. I didn't see any errors logged by the listener on deploy or undeploy except for:
Internal registry of java.beans.PropertyEditorManager not found

I like the changes.

**Comment by mjiderhamn** [comment]
Version 1.11.0 that includes these changes have now been released.

**Comment by LukeWoodward** [comment]
Sorry, I don't believe this issue has been fixed.  As far as I can see there is still a leak that causes webapp classloaders not to be garbage collected.

Courtesy of JVisualVM, here's a path from a (destroyed) Tomcat WebappClassLoader to a GC root:

    this     - value: org.apache.catalina.loader.WebappClassLoader #1
     <- <classLoader>     - class: example.ClassLoaderLeakPreventor$2, value: org.apache.catalina.loader.WebappClassLoader #1
      <- <class>     - class: example.ClassLoaderLeakPreventor$2, value: example.ClassLoaderLeakPreventor$2 class ClassLoaderLeakPreventor$2
       <- combiner     - class: java.security.AccessControlContext, value: example.ClassLoaderLeakPreventor$2 #1
        <- inheritedAccessControlContext (thread object)     - class: oracle.jdbc.driver.OracleTimeoutPollingThread, value: java.security.AccessControlContext #27

Secondly, if you're using ojdbc7.jar, there is now another class that needs to be initialized in the same way that `oracle.jdbc.driver.OracleTimeoutThreadPerVM` is initialized.  This additional class is  `oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser`.  Like `OracleTimeoutThreadPerVM`, this class is a Thread.

In case it helps, I'm using JDK1.8.0_45 on Windows 10 x64, the Oracle JDBC driver jar is in `<TOMCAT_HOME>/lib`, not in `WEB-INF/lib`, and the driver JAR is being used by a test web application I've knocked up to reproduce this problem (i.e. it's not sitting around idle as it was in the initial comment on this issue).

**Comment by mjiderhamn** [comment]
Hi Luke and thanks for the report. Your trace made me realize that the DomainCombiner I created to avoid the initial ProtectionDomain issue, itself implied a reference... I have pushed changes that I hope will fix that, and also the `oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser` problem. Could you please build the library from latest sources and try it out?

**Comment by LukeWoodward** [comment]
Sorry Mattias, I'm afraid that your latest change doesn't fix the problem.  I've had a brief look into why.

Each of the two threads that the Oracle JDBC driver creates has a different AccessControlContext, nos 26 and 27 in the image below:

![image](https://cloud.githubusercontent.com/assets/2357146/10119959/4edc1436-649e-11e5-8f20-f784ef2d2453.png)

Neither 26 nor 27 is the one that the ClassLoaderLeakPreventor has a reference to (no 23). However, nos 26 and 27 both reference no 23 via a privilegedContext field:

![image](https://cloud.githubusercontent.com/assets/2357146/10119978/fcdbcaf4-649e-11e5-8c68-42fcf9cbccfb.png)

Your code nulls out the `combiner` field in no 23, but it's nos 26 and 27 that you would want to do this to instead.

**Comment by mjiderhamn** [comment]
Thanks Luke. I forgot about the inheritance of `AccessControlContext`s. I hope to have found a way around that too now. (Created a test case to look specifically at the Oracle JDBC case and it looks good). Would you care to give the version on the ['AccessControlContext' branch](https://github.com/mjiderhamn/classloader-leak-prevention/tree/AccessControlContext) a spin?

**Comment by LukeWoodward** [comment]
@mjiderhamn: the version on your AccessControlContext branch works for me.  I can now reload a test web app that talks to an Oracle database without it leaking any classloaders.

**Comment by mjiderhamn** [comment]
Thanks for verifying @LukeWoodward. Version 1.14.0 of the library should propagate to Maven Central shortly.
